name: Automated compiling of translations

on:
  push:
    branches: main
    ignore_paths:
      - "**/*.mo"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile to .mo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install gettext

      - name: Generate .mo files
        run: |
          for po_file in $(find . -name "*.po"); do
            dirname=$(dirname $po_file)
            filename=$(basename $po_file .po)
            msgfmt $po_file -o "$dirname/$filename.mo"
          done

      - name: Add .mo files to git
        run: git add .

      - name: Commit and push .mo files
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Automated .mo file generation"

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: Compiled translations
          path: /**/messages.mo

  release:
    name: Publish to release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R
