name: Automated compiling of translations

on:
  push:
    branches: main
    ignore_paths:
      - "**/*.mo"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile to .mo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install gettext -y

      - name: Generate .mo files
        run: |
          for po_file in $(find . -name "*.po"); do
            dirname=$(dirname $po_file)
            filename=$(basename $po_file .po)
            msgfmt $po_file -o "$dirname/$filename.mo"
          done

      - name: Add .mo files to git
        run: git add .

      - name: Commit and push .mo files
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Automated .mo file generation"

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: translations
          path: |
            ./**/messages.mo
            ./**/messages.po

  release:
    name: Publish to release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install gettext -y

      - name: Get translation completion for each
        working-directory: translations
        run: |
          for po_file in $(find . -name "*.po"); do
            dirname=$(dirname "$po_file")
            filename=$(basename "$po_file" .po)

            # Extract statistics from msgfmt
            statistics=$(msgfmt --statistics "$po_file")

            # Extract the number of translated and total messages
            translated_messages=$(echo "$statistics" | awk -F ',' '{print $1}' | awk '{print $1}')
            total_messages=$(echo "$statistics" | awk -F ',' '{print $2}' | awk '{print $1}')

            echo "Translated: $translated_messages"
            echo "Total: $total_messages"

            # Calculate completion percentage
            if [ -n "$translated_messages" ] && [ -n "$total_messages" ]; then
              completion_percentage=$((translated_messages * 100 / total_messages))
            else
              completion_percentage=0
            fi

            echo "Completion Percentage for $dirname: $completion_percentage%"
          done
